# Generated by Django 4.1.13 on 2024-06-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reconocimiento_facial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='objetos_usuario',
        ),
        migrations.AddField(
            model_name='objeto',
            name='usuario_objeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_reconocimiento_facial.usuario'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='programa_ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_reconocimiento_facial.programa'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='usuario_ingreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_reconocimiento_facial.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contacto_emergencia_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_reconocimiento_facial.contactoemergencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ficha_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_reconocimiento_facial.ficha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='registro_facial_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_reconocimiento_facial.registrofacial'),
        ),
    ]
